name: Daily Commit

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 03:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Modify File
        run: echo "Last run: $(date)" >> log.txt

      - name: Commit and Push Changes (21f1005029@ds.study.iitm.ac.in)
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "21f1005029@ds.study.iitm.ac.in"
          git add log.txt
          git commit -m "Automated commit: $(date)" || echo "No changes to commit"
          git push
