name: Daily Commit

on:
  schedule:
    - cron: '30 17 * * *'  # Runs daily at 17:30 UTC (11:00 PM IST)

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make a dummy commit # 21f1005029@ds.study.iitm.ac.in
        run: |
          date > date.txt
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add date.txt
          git commit -m "Daily commit $(date)"
          git push
